name: 'deploy'
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Docker: build images'
        run: make build
      - name: 'Docker: authenticate with registry'
        run: make docker-login
      - name: 'Docker: upload images'
        run: make push
      - name: 'SSH: configure agent'
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 'SSH: trust host'
        run: ssh-keyscan -H ${DEPLOY_HOST} >> ~/.ssh/known_hosts
      - name: 'Docker: deploy containers'
        run: make deploy
